name: Build

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  gradle:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} (11)

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
