name: Deploy Javadoc

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          
      - name: Generate Javadoc
        run: ./gradlew javadoc
      
      - name: test
        run: ls
     
#       - name: Deploy Javadoc
#         uses: JamesIves/github-pages-deploy-action@v4.2.2
#         with:
#           branch: gh-pages
#           folder: build/docs/javadoc
